name: Gradle

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '.run/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '.run/**'

jobs:
  build:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:

      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🔢 Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ☕ Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: 🔢 Configure
        shell: bash
        env:
          AGC_API_CONFIG: ${{ secrets.AGC_API_CONFIG }}
          AGC_APP_RELEASE_CONFIG: ${{ secrets.AGC_APP_RELEASE_CONFIG }}
          AGC_APP_DEBUG_CONFIG: ${{ secrets.AGC_APP_DEBUG_CONFIG }}
        run: |
          mkdir $GITHUB_WORKSPACE/credentials && \
          mkdir -p $GITHUB_WORKSPACE/mobile/src/huaweiDebug && \
          mkdir -p $GITHUB_WORKSPACE/mobile/src/huaweiRelease && \
          echo $AGC_API_CONFIG > $GITHUB_WORKSPACE/credentials/agc-apiclient.json && \
          echo $AGC_APP_DEBUG_CONFIG > $GITHUB_WORKSPACE/mobile/src/huaweiDebug/agconnect-services.json && \
          echo $AGC_APP_RELEASE_CONFIG > $GITHUB_WORKSPACE/mobile/src/huaweiRelease/agconnect-services.json
      - name: Build with Gradle
        env:
          AGC_PACKAGE_ID: ${{ secrets.AGC_PACKAGE_ID }}
        run: ./gradlew :build

      - name: 📦 Retain Artifact (JAR)
        id: retain-plugin-jar
        uses: actions/upload-artifact@v3
        with:
          name: agconnect-publishing-gradle-plugin
          path: ./build/libs/*.jar
          retention-days: 14

      - name: 📦 Retain Test
        if: always()
        id: retain-plugin-test
        uses: actions/upload-artifact@v3
        with:
          name: agconnect-publishing-gradle-plugin-test
          path: ./build/reports/tests/test
          retention-days: 1
