name: Gradle

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '.run/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '.run/**'

jobs:
  build:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:

      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🔢 Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ☕ Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: 🔢 Set up config files
        shell: bash
        env:
          AGC_PACKAGE_ID:  ${{ secrets.AGC_PACKAGE_ID }}
          AGC_API_CONFIG: ${{ secrets.AGC_API_CONFIG }}
          AGC_APP_RELEASE_CONFIG: ${{ secrets.AGC_APP_RELEASE_CONFIG }}
          AGC_APP_DEBUG_CONFIG:  ${{ secrets.AGC_APP_DEBUG_CONFIG }}
        run: echo $AGC_PACKAGE_ID

      - name: Build with Gradle
        env:
          AGC_PACKAGE_ID:  ${{ secrets.AGC_PACKAGE_ID }}
        run: ./gradlew :build

      - name: 📦 Retain Artifact (JAR)
        id: retain-plugin-jar
        uses: actions/upload-artifact@v3
        with:
          name: agconnect-publishing-gradle-plugin
          path: ./build/libs/*.jar
          retention-days: 14
