name: Gradle

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '.run/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '.run/**'

jobs:
  build:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:

      # Testing the plugin source requires checking out into `buildSrc`.
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          path: 'buildSrc'

      - name: 🔢 Configure
        shell: bash
        env:
          JAVA_KEYSTORE_DEBUG: ${{ secrets.JAVA_KEYSTORE_DEBUG }}
          JAVA_KEYSTORE_UPLOAD: ${{ secrets.JAVA_KEYSTORE_UPLOAD }}
          JAVA_KEYSTORE_PROPERTIES: ${{ secrets.JAVA_KEYSTORE_PROPERTIES }}
          AGC_API_CONFIG: ${{ secrets.AGC_API_CONFIG }}
          AGC_APP_RELEASE_CONFIG: ${{ secrets.AGC_APP_RELEASE_CONFIG }}
          AGC_APP_DEBUG_CONFIG: ${{ secrets.AGC_APP_DEBUG_CONFIG }}
        run: |
          mkdir ~/.android
          echo $JAVA_KEYSTORE_DEBUG > ~/.android/debug.keystore && \
          echo $JAVA_KEYSTORE_UPLOAD > ~/.android/upload.keystore && \
          echo $JAVA_KEYSTORE_PROPERTIES > $GITHUB_WORKSPACE/keystore.properties && \
          mv ./buildSrc/settings.gradle ./settings.gradle && \
          mv ./buildSrc/gradle.properties ./gradle.properties && \
          mv ./buildSrc/gradle ./gradle && \
          mv ./buildSrc/gradlew.bat ./gradlew.bat && \
          mv ./buildSrc/gradlew ./gradlew && \
          chmod +x ./gradlew
          mkdir $GITHUB_WORKSPACE/credentials && \
          mkdir -p $GITHUB_WORKSPACE/mobile/src/huaweiDebug && \
          mkdir -p $GITHUB_WORKSPACE/mobile/src/huaweiRelease && \
          echo $AGC_API_CONFIG > $GITHUB_WORKSPACE/credentials/agc-apiclient.json && \
          echo $AGC_APP_DEBUG_CONFIG > $GITHUB_WORKSPACE/mobile/src/huaweiDebug/agconnect-services.json && \
          echo $AGC_APP_RELEASE_CONFIG > $GITHUB_WORKSPACE/mobile/src/huaweiRelease/agconnect-services.json

      - name: ☕ Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        env:
          AGC_PACKAGE_ID: ${{ secrets.AGC_PACKAGE_ID }}
        run: |
          ./gradlew :build
          ls -la
      - name: 📦 Retain Artifact (JAR)
        id: retain-plugin-jar
        uses: actions/upload-artifact@v3
        with:
          name: buildSrc
          path: ./buildSrc/build/libs/*.jar
          retention-days: 14

      - name: 📦 Retain Test Result
        if: always()
        id: retain-plugin-test
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ./buildSrc/build/reports/tests/test
          retention-days: 1
